# =================================================================
# Deployment Kubernetes LOCAL pour le frontend Angular
# Configuration adaptée pour Minikube / environnement local
# =================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
    tier: web
    environment: local
spec:
  replicas: 1  # 1 seul replica pour local
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        environment: local
    spec:
      containers:
      - name: frontend
        # Image locale
        image: vitrine-frontend:local
        imagePullPolicy: Never  # Utilise l'image locale
        ports:
        - containerPort: 80
          name: http

        # Variables d'environnement
        env:
        - name: API_URL
          value: "http://localhost:30080/api"  # URL via NodePort

        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

        # Ressources minimales
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
# Service pour frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app: frontend
    environment: local
spec:
  type: NodePort  # NodePort pour accès local
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081  # Port fixe pour accès via minikube
    name: http
