# =================================================================
# Configuration Grafana Mimir - Métriques à long terme
# =================================================================

multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

distributor:
  pool:
    health_check_ingesters: true

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

limits:
  max_global_series_per_user: 1000000
  ingestion_rate: 100000
  ingestion_burst_size: 200000

# API compatibilité Prometheus
api:
  prometheus_http_prefix: /prometheus
